name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -
        echo "${HOME}/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies and activate virtual environment
      shell: bash
      run: |
        cd homework-1
        poetry install
        source $(poetry env info --path)/bin/activate
        
        cd ..
        make run_and_test
